version: '3.8'
services:
  java-app:
    image: {IMAGE}
    ports:
      - 8080:8080
  mysql:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  
